# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '53ce9dcd-8e6b-4614-ac56-2f82019211df'
  imageRepository: 'fnproject'
  containerRegistry: 'sangngoacr.azurecr.io'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'sangngoacr96a9-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildWebApp
    displayName: 'Build and push webapp image'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'webapp'
        dockerfile: '**/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: UploadManifests
    displayName: 'Upload manifests'
    steps:
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'fnproject.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              sed -i "s|{{DOCKER_IMAGE_VERSION}}|$(Build.BuildId)|g" $(Pipeline.Workspace)/manifests/web.yml
              cat $(Pipeline.Workspace)/manifests/web.yml
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/db.yml
                $(Pipeline.Workspace)/manifests/web.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

