version: '3'
services:
  app:
    build: ./
    ports: 
      - "8888:80"
    depends_on:
      - app-db
    environment:
      - MYSQL_HOSTNAME=app-db
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=is207_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  app-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=is207_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user